language: go
go:
  - '1.10'
install:
  - go get -t -v $(go list ./... | grep -v /examples)
script:
  - go vet $(go list ./... | grep -v /examples)
  - go test -race -v $(go list ./... | grep -v /examples)
